repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: istio
    url: git+https://github.com/istio/istio@manifests/charts?sparse=0&ref=1.8.0
  - name: istio-control
    url: git+https://github.com/istio/istio@manifests/charts/istio-control?sparse=0&ref=1.8.0
  - name: istio-gateways
    url: git+https://github.com/istio/istio@manifests/charts/gateways?sparse=0&ref=1.8.0
  - name: kiali
    url: https://kiali.org/helm-charts

releases:
  - name: metrics-server
    chart: bitnami/metrics-server
    values:
      - apiService:
          create: true

  # Installs cert-manager for automatic certificate management
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    createNamespace: true
    values:
      - installCRDs: true

  # Create a cluster wide global certificate issuer that relies on
  # https01 for verifying domains
  - name: cluster-issuer
    chart: incubator/raw
    namespace: cert-manager
    needs:
      - cert-manager/cert-manager
    values:
      - resources:
          - apiVersion: cert-manager.io/v1alpha2
            kind: ClusterIssuer
            metadata:
              name: letsencrypt
            spec:
              acme:
                server: https://acme-v02.api.letsencrypt.org/directory
                email: AaronBatilo@gmail.com
                privateKeySecretRef:
                  name: letsencrypt
                solvers:
                  - http01:
                      ingress:
                        class: istio

  # Installs istio base components
  - name: istio-base
    chart: istio/base
    namespace: istio-system
    createNamespace: true # Create the istio-system namespace for me

  # Installs istiod
  - name: istio-discovery
    chart: istio-control/istio-discovery
    namespace: istio-system
    needs:
      - istio-system/istio-base
    values:
      - global:
          hub: docker.io/istio # default to using testing container
          tag: 1.8.0

  # Creates istio-ingressgateway for routing traffic into the cluster
  - name: istio-ingress
    chart: istio-gateways/istio-ingress
    namespace: istio-system
    needs:
      - istio-system/istio-base
      - istio-system/istio-discovery
    values:
      - global:
          hub: docker.io/istio # default to using testing container
          tag: 1.8.0

  # Responds to http01 challenges globally for us
  # Not to be used by any applications.
  - name: global-gateway
    chart: incubator/raw
    namespace: istio-system
    needs:
      - istio-system/istio-base
    values:
      - resources:
          - apiVersion: networking.istio.io/v1beta1
            kind: Gateway
            metadata:
              name: global-gateway
              labels:
                app: ingressgateway
            spec:
              selector:
                istio: ingressgateway
              servers:
                - port:
                    number: 80
                    protocol: HTTP
                    name: http
                  hosts:
                    - "*"

  - name: kiali-server
    namespace: istio-system
    chart: kiali/kiali-server
    values:
      - auth:
          strategy: anonymous
